# Generated by Django 2.2.3 on 2021-08-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210818_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '未知'), (2, '女')], verbose_name='性别'),
        ),
    ]
