# Generated by Django 2.2 on 2021-09-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210902_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(2, '女'), (1, '男'), (0, '未知')], verbose_name='性别'),
        ),
    ]
