# Generated by Django 2.2 on 2021-09-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210906_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(0, '未知'), (2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(2, '拒绝'), (0, '申请'), (1, '通过')], default=0, verbose_name='审核状态'),
        ),
    ]
