# Generated by Django 2.2 on 2021-09-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210906_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(2, '女'), (1, '男'), (0, '未知')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, '通过'), (2, '拒绝'), (0, '申请')], default=0, verbose_name='审核状态'),
        ),
    ]
